import time

choice = input("The application you want to pull the account on is named tiktok, correct?:")
username = input("Alright, what's the username?:")
followers = input("How many followers do they have:")
print("Alright, pulling the account now. | Loading...")
time. sleep(2)
print("|| !! GATHERING INFO !! ||")
time. sleep(4)
print("|| !! COMPLETE !! ||")
time.sleep(0.5)
print("|| !! DOING STEPS FOR YOU !! ||")
time.sleep(0.7)
print("|| ?? ERROR ?? ||")
time.sleep(0.8)
print("|| !! RETRYING !! ||")
time.sleep(2)
print("|| !! COMPLETE !! ||")
time.sleep(0.1)
print("! [{ SYSTEM }] !: Account Has Been Pulled. There will sadly be a 1 minute wait.")
time.sleep(60)
print("Username is"+username)
print("Password is..")
time.sleep(3)
print("jx19zk")
time.sleep(10)
print("YOU GOT TROLLED AMAR")
time.sleep(0.6)
quit()
